language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t joel3rbear/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joel3rbear/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-west-2-228818898107'
  bucker_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
