sudo: required
services:
  - docker

before_install:
  - docker build -t joel3rbear/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true joel3rbear/react-test npm test

after_success:
  - docker build -t joel3rbear/multi-client ./client
  - docker build -t joel3rbear/multi-nginx ./nginx
  - docker build -t joel3rbear/multi-server ./server
  - docker build -t joel3rbear/multi-worker ./worker
  # Login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push joel3rbear/multi-client
  - docker push joel3rbear/multi-nginx
  - docker push joel3rbear/multi-server
  - docker push joel3rbear/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-228818898107
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
