version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-220-98-137.compute-1.amazonaws.com
            database: d3ulh7minu3vqj
            user: axeptwilpzbowx
            password: 4452eda355b2a2edfee4a4a699d5814d2b1b49f65e6fcd57fc83666b0837a35b
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
